# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='train.proto',
  package='grape.rpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btrain.proto\x12\tgrape.rpc\">\n\x07\x46\x65\x61ture\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x03(\x01\x12\x13\n\x0b\x66\x65\x61ture_str\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\x01\"\'\n\rPredictResult\x12\x16\n\x0epredict_result\x18\x01 \x01(\x01\"\"\n\x0bTrainResult\x12\x13\n\x0bTrainStatus\x18\x01 \x01(\x08\x32\x8f\x01\n\x0cTrainService\x12\x42\n\x10GetPredictResult\x12\x12.grape.rpc.Feature\x1a\x18.grape.rpc.PredictResult\"\x00\x12;\n\tTrainData\x12\x12.grape.rpc.Feature\x1a\x16.grape.rpc.TrainResult\"\x00(\x01\x62\x06proto3')
)




_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='grape.rpc.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='grape.rpc.Feature.feature', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_str', full_name='grape.rpc.Feature.feature_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='grape.rpc.Feature.label', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=88,
)


_PREDICTRESULT = _descriptor.Descriptor(
  name='PredictResult',
  full_name='grape.rpc.PredictResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='predict_result', full_name='grape.rpc.PredictResult.predict_result', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=129,
)


_TRAINRESULT = _descriptor.Descriptor(
  name='TrainResult',
  full_name='grape.rpc.TrainResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TrainStatus', full_name='grape.rpc.TrainResult.TrainStatus', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['PredictResult'] = _PREDICTRESULT
DESCRIPTOR.message_types_by_name['TrainResult'] = _TRAINRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:grape.rpc.Feature)
  })
_sym_db.RegisterMessage(Feature)

PredictResult = _reflection.GeneratedProtocolMessageType('PredictResult', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTRESULT,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:grape.rpc.PredictResult)
  })
_sym_db.RegisterMessage(PredictResult)

TrainResult = _reflection.GeneratedProtocolMessageType('TrainResult', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESULT,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:grape.rpc.TrainResult)
  })
_sym_db.RegisterMessage(TrainResult)



_TRAINSERVICE = _descriptor.ServiceDescriptor(
  name='TrainService',
  full_name='grape.rpc.TrainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=168,
  serialized_end=311,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPredictResult',
    full_name='grape.rpc.TrainService.GetPredictResult',
    index=0,
    containing_service=None,
    input_type=_FEATURE,
    output_type=_PREDICTRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TrainData',
    full_name='grape.rpc.TrainService.TrainData',
    index=1,
    containing_service=None,
    input_type=_FEATURE,
    output_type=_TRAINRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINSERVICE)

DESCRIPTOR.services_by_name['TrainService'] = _TRAINSERVICE

# @@protoc_insertion_point(module_scope)
