# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import train_pb2 as train__pb2


class TrainServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPredictResult = channel.unary_unary(
        '/grape.rpc.TrainService/GetPredictResult',
        request_serializer=train__pb2.Feature.SerializeToString,
        response_deserializer=train__pb2.PredictResult.FromString,
        )
    self.TrainData = channel.stream_unary(
        '/grape.rpc.TrainService/TrainData',
        request_serializer=train__pb2.Feature.SerializeToString,
        response_deserializer=train__pb2.TrainResult.FromString,
        )


class TrainServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPredictResult(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TrainData(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TrainServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPredictResult': grpc.unary_unary_rpc_method_handler(
          servicer.GetPredictResult,
          request_deserializer=train__pb2.Feature.FromString,
          response_serializer=train__pb2.PredictResult.SerializeToString,
      ),
      'TrainData': grpc.stream_unary_rpc_method_handler(
          servicer.TrainData,
          request_deserializer=train__pb2.Feature.FromString,
          response_serializer=train__pb2.TrainResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grape.rpc.TrainService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
