all: BubbleSort SelectSort InsertSort ShellSort

clean:
	 rm -f BubbleSort
	 rm -f SelectSort
	 rm -f InsertSort
	 rm -f ShellSort

BubbleSort:
	g++ BubbleSort.cpp -o BubbleSort -std=c++11
SelectSort:
	g++ SelectSort.cpp -o SelectSort -std=c++11
InsertSort:
	g++ InsertSort.cpp -o InsertSort -std=c++11
ShellSort:
	g++ ShellSort.cpp -o ShellSort -std=c++11
