all: BubbleSort SelectSort InsertSort

clean:
	 rm -f BubbleSort
	 rm -f SelectSort
	 rm -f InsertSort

BubbleSort:
	g++ BubbleSort.cpp -o BubbleSort -std=c++11
SelectSort:
	g++ SelectSort.cpp -o SelectSort -std=c++11
InsertSort:
	g++ InsertSort.cpp -o InsertSort -std=c++11
